export enum GOOGLE_CAMPAIGN_STATUS {
	ENABLED = 'ENABLED',
	PAUSED = 'PAUSED',
	REMOVED = 'REMOVED',
}

export enum GOOGLE_CAMPAIGN_TYPE {
	SEARCH = 'SEARCH',
	DISPLAY = 'DISPLAY',
	SHOPPING = 'SHOPPING',
	VIDEO = 'VIDEO',
	PERFORMANCE_MAX = 'PERFORMANCE_MAX',
	DEMAND_GEN = 'DEMAND_GEN',
	APP = 'APP',
}

export enum GOOGLE_AD_TYPE {
	RESPONSIVE_SEARCH_AD = 'RESPONSIVE_SEARCH_AD',
	RESPONSIVE_DISPLAY_AD = 'RESPONSIVE_DISPLAY_AD',
	SHOPPING_PRODUCT_AD = 'SHOPPING_PRODUCT_AD',
	VIDEO_AD = 'VIDEO_AD',
	PERFORMANCE_MAX_AD = 'PERFORMANCE_MAX_AD',
	EXPANDED_TEXT_AD = 'EXPANDED_TEXT_AD',
}

export enum GOOGLE_AD_GROUP_STATUS {
	ENABLED = 'ENABLED',
	PAUSED = 'PAUSED',
	REMOVED = 'REMOVED',
}
