export enum META_CAMPAIGN_STATUS {
	ACTIVE = 'ACTIVE',
	PAUSED = 'PAUSED',
	DELETED = 'DELETED',
	ARCHIVED = 'ARCHIVED',
}

export enum META_CAMPAIGN_OBJECTIVE {
	OUTCOME_AWARENESS = 'OUTCOME_AWARENESS',
	OUTCOME_ENGAGEMENT = 'OUTCOME_ENGAGEMENT',
	OUTCOME_LEADS = 'OUTCOME_LEADS',
	OUTCOME_SALES = 'OUTCOME_SALES',
	OUTCOME_TRAFFIC = 'OUTCOME_TRAFFIC',
	OUTCOME_APP_PROMOTION = 'OUTCOME_APP_PROMOTION',
}

export enum META_AD_STATUS {
	ACTIVE = 'ACTIVE',
	PAUSED = 'PAUSED',
	DELETED = 'DELETED',
	ARCHIVED = 'ARCHIVED',
	PENDING_REVIEW = 'PENDING_REVIEW',
	DISAPPROVED = 'DISAPPROVED',
	WITH_ISSUES = 'WITH_ISSUES',
}
